%YAML 1.2
---
sudo: false
language: python
python:
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --download-cache $HOME/.pip-cache; fi
  - pip install --download-cache $HOME/.pip-cache -r test-requirements.txt
script: nosetests --with-coverage --cover-package=formulary --cover-branches
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 2.7
    tags: true
    all_branches: true
  user: sprockets
  password:
    secure: "LlRLX0zCo57MFkOI9bqfD8Ztn0BOTbfwRzoBtiFGqZnsF/7AaHQWFaG4Ux6Y8qdOvuHtM32ZpicbjvceYwmnOVRmSBddGrmfa/SZmdQm3J2tTGI6wWw8W4Jf6mY48CkgIrm36t9jbbTg0Xsks9PMjgdh6QHw+kvFQCGNdCtmW8dOmbQNjaRTA16eP+xZp2HPCgoEKFIfxYzoa6YINlg45W4132UxAgO+JT+kJeMoyvpiJcUUO3Q1dKb3YoftqpgsZEYgnZrFPsyJYYyayfgGi7gc4THSGoYP/Ugv/rZi8KJUqO6IYd7Eqvzq2YhNcyyxeqipsmtG4YwkxiS/1PXBUvj2uO188vot7asM1OCVejBUfp0NbvWKVn7aOuwooq4u9be49FQMnK6qfkWNYQOfqCAYljwZKAJGetYx1qiRj24slLHKxiuA1loOQ4vtNz1npF8QZmDCMgCmWB8kU5ae2GmAt8XTDzTsESwNHAlCj6Bz/7hVfZ2z81X6o67Jou6a75zqQ6++VoCZBs6Aj8Bx0hr/+RHY063QaUuB5x69EAJPk2jXlqu3XdaPYlAGx/Pk9g/XzaQVv8FR5SS28eB31gpkHLA1weSdfOpFWgLc0ajKzBDEUG52lI7c8WQsZ3HTkR749pAkM8xAMNbwggDwlLYMEexJ1g60O/4fIyjunYI="

